kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: keycloak-external
spec:
  parentRefs:
    - kind: Gateway
      name: external-https
  hostnames:
    - "keycloak.35.190.9.46.nip.io"
  rules:
    - backendRefs:
        - name: keycloak
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  # podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.1
          args: ["start-dev"]
          resources:
            requests:
              cpu: "500m"
              memory: "2000Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME
              value: "keycloak.35.190.9.46.nip.io"
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-svc:5432/keycloak"
            - name: KC_HEALTH_ENABLED
              value: "true"
            # - name: DB_PORT
            #   value: "5432"
            # - name: DB_DATABASE
            #   value: keycloak
            # - name: DB_SCHEMA
            #   value: public
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-sec
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-sec
          ports:
            - name: http
              containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          #   initialDelaySeconds: 90
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          #   initialDelaySeconds: 90
          #   periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
